[Lights]
enabled=Y
# Fit-PC / production: /dev/cu.usbmodem2143301
# Arduino simulator on this Mac: /dev/cu.usbmodem21414401
comPort=/dev/cu.usbmodem21414401

[Audio]
gun=HHSCStartLine/media/1.5-Second-Horn-left.wav
warning=HHSCStartLine/media/beep-right.wav
startgun=HHSCStartLine/media/1.5-Second-Horn-left.wav
finishgun=HHSCStartLine/media/0.75-Second-Horn-left.wav

[Training]
trainingMode=N
trainingSpeed=5

[UserInterface]
backgroundColour=SkyBlue3
fullScreen=N
fontSize=16
defaultFleetNames=Large handicap,Small handicap,Toppers,Large and small handicap,Teras,Oppies

[Logging]
configFilename=HHSCStartLine/logging.conf

[Persistence]
recoveryFilename=HHSCStartLine/data/currentRace.dmp
